[package]
name = "nanochain-types"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
bytes = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
ed25519-dalek = { workspace = true }
commonware-codec = { workspace = true }
commonware-consensus = { workspace = true }
commonware-cryptography = { workspace = true }

[dev-dependencies]
rand_core = { workspace = true }
