[package]
name = "nanochain-network"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
nanochain-types = { workspace = true }
commonware-p2p = { workspace = true }
commonware-cryptography = { workspace = true }
commonware-runtime = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
